name: Shorter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db_test:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shorter_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker environment
      run: docker-compose -f docker-compose.test.yml build

    - name: Run migrations and tests
      run: |
        docker-compose -f docker-compose.test.yml run --rm --entrypoint "" app /bin/bash -c "mix ecto.setup && mix test"
